### ISSUE TITLE
Download seems to be failing

### ISSUE THREAD

**Issue by Bilb** [felixrieseberg/windows-build-tools#250]
Hi,

Running this on a github actions CI.
I get those log and I think it's the reason why I get a cryptic error later in the build (and it fails).
I am running on `windows-2016`, `node 10.19.0` and installing `windows-build-tools-version@4.0.0`

```
------------------- Python --------------------
Successfully installed Python 2.7---------- Visual Studio Build Tools ----------
[0AF8:1268][2021-05-04T00:22:06]e000: Error 0x80190194: Failed attempt to download URL: 'bits://go.microsoft.com/fwlink/?prd=12514&pver=Dev14&sbp=d14rel&plcid=0x409&clcid=0x409&ar=25420.01&sar=S80_RCPrep&o1=1F0C5812581EFDCA1A2A9C3BCE802F53D7832D6E' to: 'C:\Users\RUNNER~1\AppData\Local\Temp\{a9528995-e130-4501-ae19-bbfaddb779cc}\Msi_BuildTools_MSBuild_amd64'
[0AF8:1268][2021-05-04T00:22:06]w343: Prompt for source of package: Msi_BuildTools_MSBuild_amd64, payload: Msi_BuildTools_MSBuild_amd64, path: C:\Users\runneradmin\.windows-build-tools\packages\BuildTools_MSBuild_amd64\BuildTools_MSBuild.msi
[0AF8:1268][2021-05-04T00:22:06]i000: MUX:  Next Source: Web, Attempted: 3, Limit:3
[0AF8:1268][2021-05-04T00:22:06]i000: MUX:  Source retrieved: Web
[0AF8:1268][2021-05-04T00:22:06]i000: MUX:  Sleep for 3 seconds before retrying
```

At the end of the setup node for windows task I get
```
Could not install Visual Studio Build Tools.
Please find more details in the log files, which can be found at
C:\Users\runneradmin\.windows-build-tools

Now configuring the Visual Studio Build Tools and Python...

All done!
```

Later in the build I get
```
D:\a\...\node_modules\@journeyapps\sqlcipher\build\deps\action_before_build.vcxproj(20,3): error MSB4019: The imported project "D:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
```

Can you help me with that?

**Comment by Bilb** [comment]
Fixed it by adding the msbuild action adn switching to chocolatey

```
      - name: Chocolatey Install Action
        if: runner.os == 'Windows'
        uses: crazy-max/ghaction-chocolatey@v1.4.2
        with:
          args: install python2 visualcpp-build-tools -y

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
        if: runner.os == 'Windows'
```
